## Tâche 5 : Symmetry
Objectif : étudier l’effet de 3 éléments de symétrie différents (pas l’identité), chacun pour 1 atome différent. Repésenter-les.

In [1]:
import numpy as np
from pymatgen.ext.matproj import MPRester
from pymatgen.core.operations import SymmOp
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer
from jupyter_jsmol.pymatgen import quick_view
from IPython.display import display, Math

In [2]:
# clé API Materials Project
mp_key = "hbfwQnxIfLcB2CMDIPBvWEJViltnasHl" # Clé API
mp_id = "mp-8145"  # Identifiant matériau

In [3]:
# Téléchargement de la structure du matériau
with MPRester(mp_key) as m:
    structure = m.get_structure_by_material_id(mp_id)

Retrieving MaterialsDoc documents:   0%|          | 0/1 [00:00<?, ?it/s]

In [4]:
# Analyse de symétrie
analyzer = SpacegroupAnalyzer(structure).get_conventional_standard_structure()
symmops = SpacegroupAnalyzer(analyzer).get_space_group_operations()
Sites = structure.sites

## Représentation du RbScO2 dans la maille conventionnelle


In [5]:
view = quick_view(structure, "packed", conventional = True)
display(view)

JsmolView(layout=Layout(align_self='stretch', height='400px'))

## Opérations de symétries
On retrouve ci-dessous 3 éléments de symétries, chacun pour un atome différent. Chaque symétrie est définie par sa matrice de rotation (rot) et un vecteur de translation (tau). 

### Symétrie 1 : inversion sur Sc
Cette opération est de deuxième espèce, qui inverse donc la chiralité. On peut le vérifier en voyant que le déterminant de sa matrice associée vaut -1. Il n'y a pas de translation. On a donc comme équation :

$$
\begin{bmatrix} x & y & z \end{bmatrix}
\begin{bmatrix} -1 & 0 & 0 \\ 0 & -1 & 0 \\ 0 & 0 & -1 \end{bmatrix}
=
\begin{bmatrix} -x & -y & -z \end{bmatrix}
$$

In [6]:
i_atom = 27
i_symmop = 1

Symmetry_1 = symmops[i_symmop]
print("\nMatrice de rotation (Rot) et vecteur de translation (tau):\n")
print(Symmetry_1, "\n")
pos_depart = Sites[1].frac_coords
pos_final = Symmetry_1.operate(pos_depart)
print("Position initial de l'atome: ", pos_depart)
print("Position de l'atome après l'application de l'élément de symétrie: ", pos_final)
view = quick_view(structure,conventional = True)
display(view)
view.script('draw SYMOP ' + str(i_symmop + 1) + ' {atomno = ' + str(i_atom) + '}')



Matrice de rotation (Rot) et vecteur de translation (tau):

Rot:
[[-1.  0.  0.]
 [ 0. -1.  0.]
 [ 0.  0. -1.]]
tau
[0. 0. 0.] 

Position initial de l'atome:  [0.5 0.5 0.5]
Position de l'atome après l'application de l'élément de symétrie:  [-0.5 -0.5 -0.5]


JsmolView(layout=Layout(align_self='stretch', height='400px'))

### Symétrie 2 : Réflexion d'ordre 2 sur Rb
Cette opération est de première espèce, qui inverse donc la chiralité. On peut le vérifier en voyant que le déterminant de sa matrice associée vaut -1. Il n'y a pas de translation. On a donc comme équation :

$$
\begin{bmatrix} x & y & z \end{bmatrix}
\begin{bmatrix} 0 & -1 & 0 \\ -1 & 0 & 0 \\ 0 & 0 & 1 \end{bmatrix}
=
\begin{bmatrix} -y & -x & z \end{bmatrix}
$$

In [7]:
i_atom = 1
i_symmop = 7

Symmetry_2 = symmops[i_symmop]
print("\nMatrice de rotation (Rot) et vecteur de translation (tau):\n")
print(Symmetry_2, "\n")
pos_depart = Sites[0].frac_coords
pos_final = Symmetry_2.operate(pos_depart)
print("Position initial de l'atome: ", pos_depart)
print("Position de l'atome après l'application de l'élément de symétrie: ", pos_final)
view2 = quick_view(structure,conventional = True)
display(view2)
view2.script('draw SYMOP ' + str(i_symmop + 1) + ' {atomno = ' + str(i_atom) + '}')


Matrice de rotation (Rot) et vecteur de translation (tau):

Rot:
[[ 0. -1.  0.]
 [-1.  0.  0.]
 [ 0.  0.  1.]]
tau
[0. 0. 0.] 

Position initial de l'atome:  [-0. -0.  0.]
Position de l'atome après l'application de l'élément de symétrie:  [0. 0. 0.]


JsmolView(layout=Layout(align_self='stretch', height='400px'))

### Symétrie 3 : Rotation d'ordre 2 sur O2
Cette opération est de deuxième espèce, qui conserve donc la chiralité. On peut le vérifier en voyant que le déterminant de sa matrice associée vaut 1. Il n'y a pas de translation. On a donc comme équation :

$$
\begin{bmatrix} x & y & z \end{bmatrix}
\begin{bmatrix} 1 & -1 & 0 \\ 0 & -1 & 0 \\ 0 & 0 & -1 \end{bmatrix}
=
\begin{bmatrix} x & -x-y & -z \end{bmatrix}
$$

In [8]:
i_atom = 26
i_symmop =8

Symmetry_3 = symmops[i_symmop]
print("\nMatrice de rotation (Rot) et vecteur de translation (tau):\n")
print(Symmetry_3, "\n")
pos_depart = Sites[2].frac_coords
pos_final = Symmetry_3.operate(pos_depart)
print("Position initial de l'atome: ", pos_depart)
print("Position de l'atome après l'application de l'élément de symétrie: ", pos_final)
view3 = quick_view(structure,conventional = True)
display(view3)
view3.script('draw SYMOP ' + str(i_symmop + 1) + ' {atomno = ' + str(i_atom) + '}')


Matrice de rotation (Rot) et vecteur de translation (tau):

Rot:
[[ 1. -1.  0.]
 [ 0. -1.  0.]
 [ 0.  0. -1.]]
tau
[0. 0. 0.] 

Position initial de l'atome:  [0.77730392 0.77730392 0.77730392]
Position de l'atome après l'application de l'élément de symétrie:  [ 0.         -0.77730392 -0.77730392]


JsmolView(layout=Layout(align_self='stretch', height='400px'))